# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 737c67f21a44a009f59613f70ec8597f62f07eb84e2554889c27c48d0e32e7d024c549e368d4eb27779448c98d5404843145eaab31be2c5eb0b2e866d990f3c3

test:
  secret_key_base: 830e9feafd847801de8eedc4b211766106a9753c31973703dffa8c19c1052e6587ac2f07058820e1c3fda430c662d8f0c76bc3791364a8061a219dae7381bcbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
